### ISSUE TITLE
ModelDB search logic - change search score logic 

### ISSUE THREAD

**Issue by laeljh** [laelhalawani/glai#22]
Curretly similarity scores for name_search, quantization_search, keyword_search in ModelDB are weighted evenly.
Model name match should be prioritized over quantization and both of these over keywords

**Comment by laelhalawani** [comment]
Done and 
GGUF ModelDB has been moved to a dedicated package `gguf_modeldb` availablen on github and pypi
https://github.com/laelhalawani/gguf_modeldb
`pip install gguf_modeldb>=0.0.1a3`
